// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLcCoTrmRzO4mukwohaY-2_unTWNBM7M',
    appId: '1:129391118948:web:5aa0af79fec1dd4e04ed71',
    messagingSenderId: '129391118948',
    projectId: 'mandhiram-temple1',
    authDomain: 'mandhiram-temple1.firebaseapp.com',
    storageBucket: 'mandhiram-temple1.appspot.com',
    measurementId: 'G-N4YZRTNF8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-z7a8TJayHSUhaqurUSmOA0MyqkI4U9g',
    appId: '1:129391118948:android:e1a7ff248a1382c604ed71',
    messagingSenderId: '129391118948',
    projectId: 'mandhiram-temple1',
    storageBucket: 'mandhiram-temple1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHFtq-XtSfje23Y10OBXFEK0HgsaMJQac',
    appId: '1:129391118948:ios:4f218aa1275d8d9c04ed71',
    messagingSenderId: '129391118948',
    projectId: 'mandhiram-temple1',
    storageBucket: 'mandhiram-temple1.appspot.com',
    iosClientId: '129391118948-np9sb6i7it9g8087p3tfdtqpkgsorion.apps.googleusercontent.com',
    iosBundleId: 'com.dreamapp.templeMandhiram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHFtq-XtSfje23Y10OBXFEK0HgsaMJQac',
    appId: '1:129391118948:ios:4f218aa1275d8d9c04ed71',
    messagingSenderId: '129391118948',
    projectId: 'mandhiram-temple1',
    storageBucket: 'mandhiram-temple1.appspot.com',
    iosClientId: '129391118948-np9sb6i7it9g8087p3tfdtqpkgsorion.apps.googleusercontent.com',
    iosBundleId: 'com.dreamapp.templeMandhiram',
  );
}
